IMPORTING LIBRARIES AND READING THE FILE

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
data_5S = pd.read_csv('../labaled_features/features_5S.csv.gz', compression='gzip')
data_25S = pd.read_csv('../labaled_features/features_25S.csv.gz', compression='gzip')

In [35]:
data_5S.head()

,date,pump_index,std_rush_order,avg_rush_order,std_trades,std_volume,avg_volume,std_price,avg_price,avg_price_max,hour_sin,hour_cos,minute_sin,minute_cos,symbol,gt
0,2018-12-29 17:00:25,0,-0.002,-0.007,-0.000,0.0,-0.000,-0.001,-0.001,-0.001,-0.998,-0.068,0.000,1.000,BRD,0
1,2018-12-29 17:01:55,0,-0.002,-0.007,-0.001,-0.0,-0.002,-0.001,-0.001,-0.001,-0.998,-0.068,0.106,0.994,BRD,0
2,2018-12-29 17:02:10,0,0.000,0.000,0.000,-0.0,0.000,-0.001,-0.001,-0.001,-0.998,-0.068,0.211,0.977,BRD,0
3,2018-12-29 17:25:00,0,-0.002,-0.007,0.000,0.0,-0.000,-0.001,0.000,0.000,-0.998,-0.068,0.461,-0.887,BRD,0
4,2018-12-29 17:36:05,0,0.000,0.000,-0.000,0.0,-0.000,-0.001,0.000,0.000,-0.998,-0.068,-0.638,-0.770,BRD,0

In [36]:
data_5S.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 821307 entries, 0 to 821306
Data columns (total 16 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   date            821307 non-null  object
 1   pump_index      821307 non-null  int64
 2   std_rush_order  821307 non-null  float64
 3   avg_rush_order  821307 non-null  float64
 4   std_trades      821307 non-null  float64
 5   std_volume      821307 non-null  float64
 6   avg_volume      821307 non-null  float64
 7   std_price       821307 non-null  float64
 8   avg_price       821307 non-null  float64
 9   avg_price_max   821307 non-null  float64
 10  hour_sin        821307 non-null  float64
 11  hour_cos        821307 non-null  float64
 12  minute_sin      821307 non-null  float64
 13  minute_cos      821307 non-null  float64
 14  symbol          821307 non-null  object
 15  gt              821307 non-null  int64
dtypes: float64(12), int64(2), object(2)
memory usage: 100.3+ MB

In [37]:
data_5S.describe()

,pump_index,std_rush_order,avg_rush_order,std_trades,std_volume,avg_volume,std_price,avg_price,avg_price_max,hour_sin,hour_cos,minute_sin,minute_cos,gt
count,821307.000000,821307.000000,821307.000000,821307.000000,821307.000000,821307.000000,821307.000000,821307.000000,821307.000000,821307.000000,821307.000000,821307.000000,821307.000000,821307.000000
mean,166.040707,-0.000129,-0.000271,0.000206,0.000656,-0.000176,-0.000287,-0.000008,-0.000003,-0.121124,0.042832,-0.015121,0.022793,0.000386
std,100.273037,0.015513,0.007438,0.048085,0.099605,0.014145,0.003314,0.001104,0.001192,0.690740,0.711686,0.698909,0.714685,0.019642
min,0.000000,-0.634000,-0.500000,-0.698000,-0.864000,-0.388000,-0.127000,-0.028000,-0.027000,-0.998000,-0.991000,-1.000000,-0.999000,0.000000
25%,78.000000,0.000000,0.000000,0.000000,0.000000,-0.001000,-0.001000,-0.000000,0.000000,-0.817000,-0.577000,-0.716000,-0.698000,0.000000
50%,171.000000,0.000000,0.000000,0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000,-0.136000,-0.068000,0.000000,0.080000,0.000000
75%,255.000000,0.000000,0.000000,0.000000,-0.000000,0.000000,0.001000,0.000000,0.000000,0.520000,0.683000,0.678000,0.735000,0.000000
max,336.000000,4.710000,2.200000,15.320000,40.638000,5.134000,0.861000,0.171000,0.190000,0.998000,1.000000,1.000000,1.000000,1.000000

In [38]:
data_25S.head()

,date,pump_index,std_rush_order,avg_rush_order,std_trades,std_volume,avg_volume,std_price,avg_price,avg_price_max,hour_sin,hour_cos,minute_sin,minute_cos,symbol,gt
0,2018-12-29 17:00:25,0,-0.001,-0.005,0.0,0.000,-0.000,-0.0,-0.001,-0.001,-0.998,-0.068,0.000,1.000,BRD,0
1,2018-12-29 17:01:40,0,0.000,0.000,0.0,0.000,-0.000,-0.0,-0.001,-0.001,-0.998,-0.068,0.106,0.994,BRD,0
2,2018-12-29 17:02:05,0,0.000,0.000,0.0,-0.000,-0.002,-0.0,-0.001,-0.001,-0.998,-0.068,0.211,0.977,BRD,0
3,2018-12-29 17:25:00,0,0.000,0.000,0.0,-0.001,-0.004,-0.0,0.000,0.000,-0.998,-0.068,0.461,-0.887,BRD,0
4,2018-12-29 17:35:50,0,0.000,0.000,-0.0,-0.000,0.000,-0.0,0.000,0.000,-0.998,-0.068,-0.553,-0.833,BRD,0

In [39]:
data_25S.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482157 entries, 0 to 482156
Data columns (total 16 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   date            482157 non-null  object
 1   pump_index      482157 non-null  int64
 2   std_rush_order  482157 non-null  float64
 3   avg_rush_order  482157 non-null  float64
 4   std_trades      482157 non-null  float64
 5   std_volume      482157 non-null  float64
 6   avg_volume      482157 non-null  float64
 7   std_price       482157 non-null  float64
 8   avg_price       482157 non-null  float64
 9   avg_price_max   482157 non-null  float64
 10  hour_sin        482157 non-null  float64
 11  hour_cos        482157 non-null  float64
 12  minute_sin      482157 non-null  float64
 13  minute_cos      482157 non-null  float64
 14  symbol          482157 non-null  object
 15  gt              482157 non-null  int64
dtypes: float64(12), int64(2), object(2)
memory usage: 58.9+ MB

In [40]:
data_25S.describe()

,pump_index,std_rush_order,avg_rush_order,std_trades,std_volume,avg_volume,std_price,avg_price,avg_price_max,hour_sin,hour_cos,minute_sin,minute_cos,gt
count,482157.000000,482157.000000,482157.000000,482157.000000,482157.000000,482157.000000,482157.000000,482157.000000,482157.000000,482157.000000,482157.000000,482157.000000,482157.000000,482157.000000
mean,163.651914,0.000456,-0.000110,0.000933,0.002112,0.000097,-0.000135,-0.000014,-0.000006,-0.083772,0.028490,-0.012240,0.023586,0.000657
std,98.853939,0.059436,0.007755,0.098056,0.219304,0.022000,0.004577,0.001459,0.002069,0.693841,0.714758,0.698921,0.714692,0.025633
min,0.000000,-0.546000,-0.255000,-0.543000,-0.774000,-0.405000,-0.360000,-0.024000,-0.025000,-0.998000,-0.991000,-1.000000,-0.999000,0.000000
25%,77.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.001000,-0.001000,-0.001000,-0.731000,-0.577000,-0.716000,-0.698000,0.000000
50%,168.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.136000,-0.068000,0.000000,0.080000,0.000000
75%,248.000000,0.000000,0.000000,-0.000000,0.000000,0.000000,0.001000,0.000000,0.000000,0.631000,0.683000,0.678000,0.735000,0.000000
max,336.000000,15.510000,1.294000,30.708000,71.043000,6.658000,1.756000,0.311000,0.916000,0.998000,1.000000,1.000000,1.000000,1.000000

In [41]:

print('data_5S.shape:', data_5S.shape)
print('data_25S.shape:', data_25S.shape)

data_5S.shape: (821307, 16)
data_25S.shape: (482157, 16)

In [42]:
print('data_5S.columns:', data_5S.columns)
print('data_25S.columns:', data_25S.columns)

data_5S.columns: Index(['date', 'pump_index', 'std_rush_order', 'avg_rush_order', 'std_trades',
       'std_volume', 'avg_volume', 'std_price', 'avg_price', 'avg_price_max',
       'hour_sin', 'hour_cos', 'minute_sin', 'minute_cos', 'symbol', 'gt'],
      dtype='object')
data_25S.columns: Index(['date', 'pump_index', 'std_rush_order', 'avg_rush_order', 'std_trades',
       'std_volume', 'avg_volume', 'std_price', 'avg_price', 'avg_price_max',
       'hour_sin', 'hour_cos', 'minute_sin', 'minute_cos', 'symbol', 'gt'],
      dtype='object')

In [43]:
print("5S dataset - Class distribution:")
print(data_5S['gt'].value_counts())
print("\n25S dataset - Class distribution:")
print(data_25S['gt'].value_counts())

5S dataset - Class distribution:
0    820990
1       317
Name: gt, dtype: int64

25S dataset - Class distribution:
0    481840
1       317
Name: gt, dtype: int64

In the ground truth label 0=Normal while 1=Pump

In [44]:
# Prepare the data for modeling
#drop non-numeric columns
X_5S = data_5S.drop(columns=['gt', 'symbol', 'date'])
y_5S = data_5S['gt']

X_25S = data_25S.drop(columns=['gt', 'symbol', 'date'])
y_25S = data_25S['gt']

Note: The code above loads the datasets, performs basic exploratory data analysis (EDA) by checking the shape, columns, and class distribution of the datasets, and prepares the data for modeling by separating the features (X) and target variable (y).

Does window size affect Pump Detection Performance?

In [48]:
#check class imbalance
print('5S Class Distribution:')
print(y_5S.value_counts(normalize=True))

print('25S Class Distribution:')
print(y_25S.value_counts(normalize=True))

5S Class Distribution:
0    0.999614
1    0.000386
Name: gt, dtype: float64
25S Class Distribution:
0    0.999343
1    0.000657
Name: gt, dtype: float64

In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

logreg_5S = LogisticRegression(max_iter=1000, random_state=42)

# Train ONLY on training data
logreg_5S.fit(X5_train, y5_train)

# Predict ONLY on test data
y5_pred = logreg_5S.predict(X5_test)

print("5S Logistic Regression Results:")
print(classification_report(y5_test, y5_pred))

5S Logistic Regression Results:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    164199
           1       0.91      0.48      0.62        63

    accuracy                           1.00    164262
   macro avg       0.95      0.74      0.81    164262
weighted avg       1.00      1.00      1.00    164262

In [52]:
from sklearn.model_selection import train_test_split

# 5S Split
X5_train, X5_test, y5_train, y5_test = train_test_split(
    X_5S, y_5S, test_size=0.2, stratify=y_5S, random_state=42
)

# 25S Split
X25_train, X25_test, y25_train, y25_test = train_test_split(
    X_25S, y_25S, test_size=0.2, stratify=y_25S, random_state=42
)

# Apply SMOTE ONLY to training data
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X5_train_res, y5_train_res = smote.fit_resample(X5_train, y5_train)
X25_train_res, y25_train_res = smote.fit_resample(X25_train, y25_train)

In [54]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
rf_5S = RandomForestClassifier(n_estimators=100, random_state=42)
rf_5S.fit(X5_train_res, y5_train_res)
y5_pred = rf_5S.predict(X5_test)
print("5S Classification Report:")
print(classification_report(y5_test, y5_pred))

5S Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    164199
           1       0.76      0.86      0.81        63

    accuracy                           1.00    164262
   macro avg       0.88      0.93      0.90    164262
weighted avg       1.00      1.00      1.00    164262

In [55]:
rf_25 = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_25.fit(X25_train_res, y25_train_res)

y25_pred = rf_25.predict(X25_test)

print("25S Random Forest Results:")
print(classification_report(y25_test, y25_pred))

25S Random Forest Results:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     96369
           1       0.87      0.86      0.86        63

    accuracy                           1.00     96432
   macro avg       0.94      0.93      0.93     96432
weighted avg       1.00      1.00      1.00     96432